name: Sync GitHub To Gitee

on:
  push:
    branches:
      - main
      - develop

  workflow_dispatch:


jobs:
  mirror:
    name: Mirror Repository
    runs-on: ubuntu-latest

    steps:
      - name: Sync GitHub repository to Gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/linphone-young
          dst: gitee/yang-lingfeng

          static_list: Text2Voice_local_html

          dst_key: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}

          force_update: true

          debug: true
